output_path: "/result/results/"
output_name: "2024460_Mosaik_RGB.tif"


input_img_path: "/data/orthofotos/2024460_Mosaik_RGB.tif"
channels: [1, 2, 3]

img_pixels_detection: 2048
margin: 128
output_type: "argmax"
n_classes: 19


model_weights: "/home/eouser/FLAIR-1/flair_cosia_swin-small-rgb_upernet_custom.ckpt"
model_framework:
    model_provider: HuggingFace

    HuggingFace:
        org_model: openmmlab/upernet-swin-small
    SegmentationModelsPytorch:
        encoder_decoder: resnet34_unet


batch_size: 1
use_gpu: true
num_worker: 8

write_dataframe: False

norma_task:
  - norm_type: custom
    norm_means: [105.35, 111.31, 102.09]
    norm_stds: [52.34, 45.63, 44.39]

